services:
    ollama:
        image: ollama/ollama
        container_name: ollama
        ports:
            - '11434:11434'
        pull_policy: always
        tty: true
        volumes:
            - ollama-data:/root/.ollama
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
        entrypoint: /bin/sh -c "/bin/ollama serve & sleep 5 && ollama pull llama3.2 && wait"
        healthcheck:
            test: ['CMD-SHELL', 'curl -f http://localhost:11434/api/tags || exit 1']
            interval: 10s
            timeout: 5s
            retries: 5
        restart: unless-stopped

    redis:
        container_name: redis
        image: redis:7-alpine
        restart: always
        command: ['redis-server', '--appendonly', 'yes']
        ports:
            - '6379:6379'
        volumes:
            - redis-data:/data
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    ollama-data:
    redis-data:
